### ISSUE TITLE
Error on running test.py

### ISSUE THREAD

**Issue by pieterjanverbruggen** [mdengler/cla#1]
I am trying to run your test with Python 2.7 and get following error:

Traceback (most recent call last):
  File "./test.py", line 96, in <module>
    main(args)
  File "./test.py", line 72, in main
    cla.solve()
  File "C:\Users\user\Downloads\cla-master\CLA.py", line 78, in solve
    self.w[-1][i])
  File "C:\Users\user\Downloads\cla-master\CLA.py", line 162, in computeLambda
    if wB==None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by pieterjanverbruggen** [comment]
This can be fixed by replacing == by 'is' on line
CLA.py 136 and 162
if wB is None

**Comment by mdengler** [comment]
Thanks -- committed as 6096d19
